apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc
  namespace: argocd
spec:
  project: default
  source:
    # Reference external helm chart here, with values taken from local file
    chart: cp-microservice
    repoURL: https://github.com/mhindery/charts/
    targetRevision: 0.0.2
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: poc
