# App of apps root per environment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment-poc
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/poc
    repoURL: "https://github.com/mhindery/argo.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
